mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

command:
  name: otelcol-contrib
  extraArgs:
  - --feature-gates=receiver.prometheusreceiver.EnableNativeHistograms

clusterRole:
  create: true
  rules:
  - apiGroups: [""]
    resources: [pods, nodes]
    verbs: [get, list, watch]

config:
  exporters:
    debug:
      verbosity: basic
    prometheusremotewrite/kube-prometheus-stack:
      endpoint: http://kube-prometheus-stack-prometheus.telemetry.svc:9090/api/v1/write

  processors:
    transform/info-suffix:
      metric_statements:
      - context: metric
        statements:
        - set(metric.name, Concat([metric.name, "info"], "_")) where metric.metadata["prometheus.type"] == "info"

  receivers:
    prometheus/agentgateway-controlplane:
      config:
        global:
          scrape_protocols:
          - PrometheusProto
          - OpenMetricsText1.0.0
          - OpenMetricsText0.0.1
          - PrometheusText0.0.4
        scrape_configs:
        - job_name: agentgateway-controlplane
          honor_labels: true
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_agentgateway]
            regex: agentgateway
          - action: keep
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
          - action: replace
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_ip
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            separator: ':'
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

    prometheus/agentgateway-dataplane:
      config:
        global:
          scrape_protocols:
          - PrometheusProto
          - OpenMetricsText1.0.0
          - OpenMetricsText0.0.1
          - PrometheusText0.0.4
        scrape_configs:
        - job_name: agentgateway-dataplane
          honor_labels: true
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_gateway_networking_k8s_io_gateway_class_name]
            regex: agentgateway
          - action: keep
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
          - action: replace
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_ip
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            separator: ':'
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

  service:
    pipelines:
      metrics:
        receivers:
        - prometheus/agentgateway-dataplane
        - prometheus/agentgateway-controlplane
        processors:
        - transform/info-suffix
        - batch
        exporters:
        - debug
        - prometheusremotewrite/kube-prometheus-stack
